### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by sydat2701** [GistNoesis/FourierKAN#3]
Hi, can you please tell me your version of pytorch and torch_geometric? I run your code with my env but it rendered the error " AttributeError: Can't get attribute 'DataEdgeAttr' on <module 'torch_geometric.data.data' from 'C:\\Users\\icml\\anaconda3\\envs\\datts\\lib\\site-packages\\torch_geometric\\data\\data.py'>".

Thanks!

**Comment by unrealwill** [comment]
Any torch version should work, as it is only doing a basic sum. My code doesn't use torch_geometric.

You probably have an unrelated issue with your anaconda env, or you posted your issue on the wrong thread.

I am on linux.
```
import torch as th
>>> th.__version__
'2.2.1+cu121'
```

Closing as unrelated.
